- name: reload systemd
  systemd:
    daemon_reload: yes
- name: restart captagent
  systemd:
    name: captagent
    state: restarted
- name: enable captagent
  systemd:
    name: captagent
    enabled: yes
